import "@/styles/globals.css";
import { type Metadata } from "next";
import { TRPCReactProvider } from "@/trpc/react";
import { ChakraProviders } from "@/provider/ChakraProviders";
import { GlobalStoreProvider } from "@/provider/GlobalStoreProvider";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: process.env.APP_NAME,
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <GlobalStoreProvider>
          <ChakraProviders>
            <TRPCReactProvider>
              <Suspense>
                {children}
              </Suspense>
            </TRPCReactProvider>
          </ChakraProviders>
        </GlobalStoreProvider>
      </body>
    </html>
  );
}
